pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "hw:Headphones,0"
    }
    capture.pcm {
        type plug
        slave.pcm "hw:Device,0"
    }
}
ctl.!default {
    type hw
    card Headphones
}
